@testable import LightamerCore
import CoreImage
import LightamerIOP
import Metal
import XCTest

/// RAW-03 (Plan 02-06-06): 32-bit float TIFF/EXR decode with BIT-DEPTH
/// preservation into the pixelpipe input plane (HDR/stack sources).
///
/// Fixtures (committed + generated by `Scripts/gen-float-fixtures.py`):
/// 64×64 float32 RGB, channel-equal gray with pinned extreme pixels
/// 0.0 / 0.5 / 1.0 / 2.0 / 65504.0 — the >1.0 values MUST survive into the
/// float32 pipe (D-COL4: clamp only at gamma).
///
/// **Host decision recorded at `RAWDecoder.decodeRaster` (2026-09-19):** the
/// CGImage path preserves float32 for both UTIs (bpp=32/96 TIFF, bpp=32/128
/// EXR, extendedLinearSRGB) — the `CIImage(contentsOf:)` fallback is NOT
/// adopted. The tests below pin that behavior as the regression gate.
///
/// Gray pixels rationale: a channel-equal value is numerically INVARIANT
/// under any white-point-preserving linear RGB→RGB conversion, so the pinned
/// values survive the extendedLinearSRGB → linear-Rec2020 input leg exactly,
/// independent of how the untagged file's space is interpreted.
final class RAW03Tests: XCTestCase {

    /// The pinned (x, y, value) table — MUST match
    /// `Scripts/gen-float-fixtures.py` (the generator prints the same table).
    static let pinnedPixels: [(x: Int, y: Int, value: Float)] = [
        (8, 8, 0.0),
        (16, 16, 0.5),
        (24, 24, 1.0),
        (32, 32, 2.0),
        (40, 40, 65504.0),
    ]

    /// Float32 comparison: absolute epsilon for near-1 values, relative for
    /// the 65504 extremes (conversion error scales with magnitude).
    private func assertValue(
        _ actual: Float, equals expected: Float, _ context: String,
        file: StaticString = #filePath, line: UInt = #line
    ) {
        let tolerance = max(1e-3, abs(expected) * 1e-4)
        XCTAssertEqual(
            actual, expected, accuracy: tolerance, context,
            file: file, line: line
        )
    }

    private func sample(
        _ texture: any MTLTexture, x: Int, y: Int, float32: Bool
    ) -> Float {
        let bytesPerPixel = float32 ? 16 : 4
        let rowBytes = texture.width * bytesPerPixel
        var row = [UInt8](repeating: 0, count: rowBytes)
        texture.getBytes(
            &row, bytesPerRow: rowBytes,
            from: MTLRegionMake2D(0, y, texture.width, 1), mipmapLevel: 0
        )
        if float32 {
            return row.withUnsafeBytes { $0.load(fromByteOffset: x * 16, as: Float.self) }
        }
        return Float(row[x * 4 + 1]) / 255 // green channel of BGRA8
    }

    private func decode(_ name: String, _ ext: String) async throws -> DecodedImage {
        try await decode(url: Fixtures.raster(name, ext))
    }

    private func decode(url: URL) async throws -> DecodedImage {
        let decoder = RAWDecoder()
        return try await decoder.decode(url)
    }

    /// GPU completion fence — getBytes does not wait for in-flight encoders
    /// (LESSONS L014); every readback here drains first.
    private func drain(_ metal: MetalContext) {
        let fence = metal.commandQueue.makeCommandBuffer()
        fence?.commit()
        fence?.waitUntilCompleted()
    }

    // ── 1. Decode-level: the CGImage path keeps float32 ──────────────────

    func testFloatTIFFDecodesWithFullBitDepth() async throws {
        let decoded = try await decode("float32-gradient", "tif")
        XCTAssertEqual(decoded.capture.width, 64)
        XCTAssertEqual(decoded.capture.height, 64)
    }

    func testFloatEXRDecodesWithFullBitDepth() async throws {
        let decoded = try await decode("float32-gradient", "exr")
        XCTAssertEqual(decoded.capture.width, 64)
        XCTAssertEqual(decoded.capture.height, 64)
    }

    // ── 2. Pipe-level: pinned extremes survive into the input plane ─────

    /// The trio-less pipe output IS the float32 input plane (linear
    /// Rec2020): every pinned value — INCLUDING 2.0 and 65504.0 — must be
    /// present pre-gamma (D-COL4's "pipe never truncates" evidence).
    func testPipeInputPlanePreservesExtremeValuesTIFF() async throws {
        try XCTSkipIf(MTLCreateSystemDefaultDevice() == nil, "no Metal GPU")
        let decoded = try await decode("float32-gradient", "tif")
        let metal = try MetalContext()
        let (plane, _) = try await RenderPipeline.process(
            image: decoded, instances: [], imageID: UUID(),
            resolution: .preview, cache: PipeCache(), metal: metal, longEdge: 64
        )
        drain(metal)
        XCTAssertEqual(plane.pixelFormat, WorkingSpace.pixelFormat)
        for (x, y, expected) in Self.pinnedPixels {
            assertValue(
                sample(plane, x: x, y: y, float32: true), equals: expected,
                "TIFF input plane (\(x),\(y)) must be \(expected)"
            )
        }
    }

    func testPipeInputPlanePreservesExtremeValuesEXR() async throws {
        try XCTSkipIf(MTLCreateSystemDefaultDevice() == nil, "no Metal GPU")
        let decoded = try await decode("float32-gradient", "exr")
        let metal = try MetalContext()
        let (plane, _) = try await RenderPipeline.process(
            image: decoded, instances: [], imageID: UUID(),
            resolution: .preview, cache: PipeCache(), metal: metal, longEdge: 64
        )
        drain(metal)
        for (x, y, expected) in Self.pinnedPixels {
            assertValue(
                sample(plane, x: x, y: y, float32: true), equals: expected,
                "EXR input plane (\(x),\(y)) must be \(expected)"
            )
        }
    }

    // ── 3. D-COL4: >1.0 survives the modules; gamma is THE clamp point ──

    /// With [colorin, testgain(1.0), colorout] — no gamma — the >1.0 values
    /// ride through the whole float32 interior untouched.
    func testInteriorStagesDoNotClampAboveOne() async throws {
        try XCTSkipIf(MTLCreateSystemDefaultDevice() == nil, "no Metal GPU")
        let decoded = try await decode("float32-gradient", "exr")
        let metal = try MetalContext()
        try await metal.registerDefaultLibrary(in: TestGainKernel.metalBundle)

        let colorin = ModuleBox(module: ColorInModule(), instanceID: UUID())
        await colorin.setParams(.init())
        let gain = ModuleBox(module: TestGainModule(), instanceID: UUID())
        await gain.setParams(.init(gain: 1.0)) // identity gain
        let colorout = ModuleBox(module: ColorOutModule(), instanceID: UUID())
        await colorout.setParams(.init(outputProfile: .displayP3)) // fast path: no CI race leg

        let (plane, _) = try await RenderPipeline.process(
            image: decoded, instances: [colorin, gain, colorout], imageID: UUID(),
            resolution: .preview, cache: PipeCache(), metal: metal, longEdge: 64
        )
        drain(metal)
        assertValue(
            sample(plane, x: 32, y: 32, float32: true), equals: 2.0,
            "interior (pre-gamma) plane keeps 2.0"
        )
        assertValue(
            sample(plane, x: 40, y: 40, float32: true), equals: 65504.0,
            "interior (pre-gamma) plane keeps 65504.0 — D-COL4 no-truncation"
        )
    }

    /// The inverse bound: through the FULL chain the gamma tail CLAMPS the
    /// >1.0 values to display white (D-COL4's "gamma is THE clamp point"),
    /// and the 0.0/0.5/1.0 values encode per the sRGB TRC.
    func testGammaTailClampsAboveOne() async throws {
        try XCTSkipIf(MTLCreateSystemDefaultDevice() == nil, "no Metal GPU")
        let decoded = try await decode("float32-gradient", "tif")
        let metal = try MetalContext()
        let registry = ModuleRegistry.makeDefault()
        let chain = await registry.makeDefaultChain()
        for box in chain {
            if let colorout = box as? ModuleBox<ColorOutModule> {
                colorout.module.displayProfileOverride = .sRGB // deterministic fast path
                await colorout.setParams(.init(outputProfile: .sRGB))
            }
        }

        let (plane, _) = try await RenderPipeline.process(
            image: decoded, instances: chain, imageID: UUID(),
            resolution: .preview, cache: PipeCache(), metal: metal, longEdge: 64
        )
        drain(metal)
        XCTAssertEqual(plane.pixelFormat, GammaModule.outputPixelFormat)
        // sample() returns the NORMALIZED 8-bit value (byte/255).
        let white = sample(plane, x: 32, y: 32, float32: false)
        let superWhite = sample(plane, x: 40, y: 40, float32: false)
        XCTAssertEqual(white, 1.0, accuracy: 1.0 / 255, "1.0 encodes to display white (byte 255)")
        XCTAssertEqual(superWhite, 1.0, accuracy: 1.0 / 255, ">1.0 clamps at gamma (D-COL4)")
    }

    // ── 4. HIF/HEIC decode (RAW-03's "读取" claim; documented limitation)

    /// RAW-03 names HIF alongside TIFF/EXR. ImageIO decodes HEIF/HIF
    /// natively — but NO encoder on this host writes a 32-bit float HIF
    /// fixture (HEIF float is 10/12-bit integer + half-float variants only),
    /// so the bit-depth claim for HIF is pinned with the strongest fixture
    /// we can commit: 16-bit HEIC decodes through the same raster path.
    /// Full float-HIF fidelity lands with a real HIF sample (Phase 8 HDR).
    func testHEICSixteenBitDecodesThroughRasterPath() async throws {
        let url = try Fixtures.raster("sample-gradient", "heic")
        let decoded = try await decode(url: url)
        XCTAssertNotNil(decoded.ciImage)
        XCTAssertGreaterThan(decoded.capture.width ?? 0, 0)
    }
}
